# Generated by Django 3.2.4 on 2021-06-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='food.food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(choices=[(1, 'не посоветую никому'), (2, 'не очень'), (3, 'нормально'), (4, 'вкусно'), (5, 'Пальчики оближешь!')])),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='food.food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('food', 'owner')},
            },
        ),
    ]
