# Generated by Django 3.2.4 on 2021-06-17 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_food_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likes_number', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='food.food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('food', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('dislikes_number', models.AutoField(primary_key=True, serialize=False)),
                ('dislike', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to='food.food')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dis_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('food', 'owner')},
            },
        ),
    ]
